services:
  croc-relay:
    image: schollz/croc
    container_name: croc-relay
    restart: always
    ports:
      - 9009-9013:9009-9013
    environment:
      - CROC_PASS=${CROC_PASS}
    network_mode: bridge
